### ISSUE TITLE
`ApiError` should be `ApiException`

### ISSUE THREAD

**Issue by Swimburger** [AssemblyAI/assemblyai-java-sdk#44]
While in our spec the name of this error is `Error`, Java seems to use the `Exception` suffix for exceptions, we should stick to that.

**Comment by Swimburger** [comment]
Any update on this?

**Comment by dcb6** [comment]
@Swimburger are you referring to the naming of [this file](https://github.com/AssemblyAI/assemblyai-java-sdk/blob/main/src/main/java/com/assemblyai/api/core/ApiError.java)?

If so, java sdk generator 1.0.1 and above have this exact improvement! Worth noting that it's possible that this could break users if they were previously catching `ApiError` anywhere in their code

**Comment by Swimburger** [comment]
@dcb6 yes, do we have to configure this somehow in 1.0.1?
It would be great if we could do it in a non-breaking change, but I don't think Java let's us alias classes or anything.

**Comment by dcb6** [comment]
1.0.1 will automatically rename your exceptions, although you can configure this if you'd like. Here's an example of this configuration in the [changelog](https://github.com/fern-api/fern/blob/main/generators/java/sdk/CHANGELOG.md#101---2024-06-26), although in that case it's showing how to avoid the break by maintaining the old error naming.

The automatic new naming for you would be, I believe, `AssemblyAIApiException`.

If you're worried about a break there are a couple options:
1. fernignore the old `ApiError`, maintaining it in the repo. This avoids compile time breaks for your customers, but would cause any try catches with that error to be effectively useless. Fwiw, we have had others of our customers do this.
2. fernignore the old `ApiError` + fernignore the new `AssemblyAIApiException`, and have `AssemblyAIApiException` extend `ApiError`. I think you'd also need to change `ApiError` extend the base error type that `AssemblyAIApiException` will extend will generate to get everything working.

I'd probably recommend (1) to reduce the amount of fernignores / complexity, but up to you.

**Comment by Swimburger** [comment]
Option 1 may not be a compile break, but it's a breaking change that silently fails which is worse than a compilation break.
Let's go with option 2 for now and introduce a breaking change in the future.

**Comment by Swimburger** [comment]
How does this look?
https://github.com/AssemblyAI/assemblyai-java-sdk/pull/117

**Comment by dcb6** [comment]
Looks great, nicely done!
