### ISSUE TITLE
RealtimeTranscriber - onPartialTranscript

### ISSUE THREAD

**Issue by srinivaskolla** [AssemblyAI/assemblyai-java-sdk#47]
onPartialTranscript is not invoking where as all the events are firing in onSessionStart

```
RealtimeTranscriber.builder()
                .apiKey(ASSEMBLY_AI_API_KEY)
                .onPartialTranscript(this::displayPartialMessage)
                .onFinalTranscript(this::displayFinalMessage)
                .onError((err) -> {
                    displayErrorMessage(err.getMessage());
                })
                .onSessionStart(System.err::println)
                .build();
```

Please help.

**Comment by dsinghvi** [comment]
@srinivaskolla thanks for filing the issue, if you upgrade to the latest version `1.0.1` this is actually fixed! I will wait for your confirmation before closing the issue!

**Comment by srinivaskolla** [comment]
Yes It is working with upgrade.

**Comment by dsinghvi** [comment]
@srinivaskolla closing this issue since you have confirmed it works!
