### ISSUE TITLE
Library does not work with java 1.8

### ISSUE THREAD

**Issue by FStupar** [AssemblyAI/assemblyai-java-sdk#52]
Although it is not stated in the repository, i am working under the assumption that the library is supposed to work on the widespead java 1.8 version. 
Unfortunately it seems that the AssemblyAI.build() method throws a NoSuchMethodException when compiled and run on java 1.8 

The issue disappears when running on JDK 21. 

Is the library supposed to work on java 1.8, and if not, what is the minimum version required?

**Comment by dsinghvi** [comment]
Hey @FStupar -- Thanks for reporting this issue. After running some tests it looks like some Java 11 changes have snuck in, if you use Java 11 does the SDK work?

AssemblyAI uses Fern (https://buildwithfern.com) for their SDKs. We will release a bugfix to make sure the SDK is compliant with 1.8 and get back to you!

**Comment by FStupar** [comment]
Yes, i can confirm that it works on 11+, and thank You!

**Comment by dsinghvi** [comment]
Closing since it is working for you @FStupar
