### ISSUE TITLE
`contentSafetyConfidence` parameter missing in `TranscriptOptionalParams`

### ISSUE THREAD

**Issue by smithakolan** [AssemblyAI/assemblyai-java-sdk#59]
Missing `contentSafetyConfidence` parameter in `TranscriptOptionalParams` class.

Desired usage example:
```java
var params = TranscriptOptionalParams.builder()
             .contentSafety(true)
             .contentSafetyConfidence(60)
             .build();
```
Parameter: contentSafetyConfidence	
Type: integer	
Description: The confidence threshold for content moderation. Values must be between 25 and 100.

Docs Usage: https://www.assemblyai.com/docs/audio-intelligence/content-moderation#adjust-the-confidence-threshold

**Comment by Swimburger** [comment]
This is missing from the spec. Adding it now.

**Comment by Swimburger** [comment]
Added to spec. We still have to figure out how to not introduce a breaking change in [this PR](https://github.com/AssemblyAI/assemblyai-java-sdk/pull/53), before we can merge in new spec changes.
CC @dsinghvi

**Comment by dsinghvi** [comment]
@Swimburger for now I'm going to use `.fernignore` to get around this

**Comment by dsinghvi** [comment]
Addressed in https://github.com/AssemblyAI/assemblyai-java-sdk/pull/62

**Comment by dsinghvi** [comment]
Now released
