### ISSUE TITLE
AssemblyAI.transcripts().transcribe() fails silently and hangs

### ISSUE THREAD

**Issue by FStupar** [AssemblyAI/assemblyai-java-sdk#60]
When providing the method with a webm audio file, the assemblyAI platfom immediately shows that the transcription failed with an error, however the method does not throw an exception, and hangs indefinitely.

**Comment by dsinghvi** [comment]
@FStupar do you mind linking a code snippet / webm audio file that we can reproduce the issue with?

**Comment by FStupar** [comment]
The code is fairly simple: 
```

            TranscriptOptionalParams config = TranscriptOptionalParams.builder()
                    .speakerLabels(true)
                    .speakersExpected(2)
                    .build();

            Transcript transcript = transcriber.transcripts().transcribe(externalFileUrl, config);
             // transcript never returns
```

**Comment by Swimburger** [comment]
The transcript should return, that's a bug we should fix.

However, our SDKs usually don't throw an exception/error when the transcript has a status of "error".
Make sure to check the status of the transcript before moving on.

**Comment by FStupar** [comment]
If it helps with identifying the problem it was a slack audio link that didn't hanged the SDK
