### ISSUE TITLE
Terminate session properly for real-time transcriber

### ISSUE THREAD

**Issue by Swimburger** [AssemblyAI/assemblyai-java-sdk#67]
Closing the real-time transcriber should send the terminate session message and wait for session termination.
Between the request for termination and confirmation for termination, partial and final transcripts will continue to come through.

**Comment by Swimburger** [comment]
@dsinghvi @smithakolan @mattmakai 
In JavaScript and .NET we can solve this by returning a `Promise` and `Task` when calling the `close` function.
How do we go about implementing this in Java? This is pretty important to get right because there could be some partial and final transcripts that are returned between ending the session and getting confirmation that the session has ended.

**Comment by SoftMemes** [comment]
This is currently blocking my companies use case for using Assembly as a slot-in replacement for Deepgram. We need to wait for the completed transcription after a user stops speaking, but do not want to wait longer than necessary.

FWIW, a CompletableFuture would do just fine for us!

**Comment by smithakolan** [comment]
@Swimburger I believe our streaming API does send the remaining transcripts upon closing. 

> After requesting session termination, the server will send the remaining transcript messages, followed by a [SessionTerminated message](https://www.assemblyai.com/docs#3-session-terminated).

**Comment by Swimburger** [comment]
This change has been released in [1.1.0](https://central.sonatype.com/artifact/com.assemblyai/assemblyai-java).
