### ISSUE TITLE
Add a way to add optional params to realtime transcriber

### ISSUE THREAD

**Issue by Sadotu** [AssemblyAI/assemblyai-java-sdk#69]
Title says it all. I want to be able to add params for different languages and also be able to turn automatic language detection on. Would it be possible to add this functionality to this SDK?

**Comment by LeeVaughn** [comment]
Hi @Sadotu!

Our Real-Time transcription feature supports English and its various dialects. It does not currently support other, non-English languages so there are no parameters for Automatic Language Detection or to specify a language.

Adding support for additional languages for Real-Time is on our Product roadmap but we do not currently have a timeline for those improvements. If you aren't already I would suggest following [our Changelog](https://www.assemblyai.com/changelog) to stay up to date on when this and other new features and improvements are released.

All the best!
