### ISSUE TITLE
Add encoding parameter to RealtimeTranscriber

### ISSUE THREAD

**Issue by Swimburger** [AssemblyAI/assemblyai-java-sdk#81]

**Comment by nrvmodi** [comment]
Yes, I am also wondering why this parameter was not added

**Comment by Swimburger** [comment]
This will be part of release 1.1.0 which will be released soon.

**Comment by Swimburger** [comment]
This change has been released in [1.1.0](https://central.sonatype.com/artifact/com.assemblyai/assemblyai-java).
